version: '3.7'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: memes_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./public-api/db/init:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  public-api:
    build: ./public-api
    command: [ "/wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    volumes:
      - ./public-api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      DATABASE_USER: memes_user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: memes
      MINIO_HOST: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  media-api:
    build: ./media-api
    command: [ "/wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001" ]
    volumes:
      - ./media-api:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      - minio
    environment:
      DATABASE_USER: memes_user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: memes
      MINIO_HOST: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  test-public-api:
    build: ./public-api
    command: [ "/wait-for-it.sh", "db:5432", "--", "pytest", "tests/test_public_api.py" ]
    volumes:
      - ./public-api:/app
    depends_on:
      - db
      - minio
    environment:
      DATABASE_USER: memes_user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: memes
      MINIO_HOST: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: [ "" ]

  test-media-api:
    build: ./media-api
    command: [ "/wait-for-it.sh", "db:5432", "--", "pytest", "tests/test_media_api.py" ]
    volumes:
      - ./media-api:/app
    depends_on:
      - db
      - minio
    environment:
      DATABASE_USER: memes_user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: memes
      MINIO_HOST: minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: [ "" ]

volumes:
  minio_data:
  db_data:
